apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storageclass
provisioner: nfs-provisioner
parameters:
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
